name: DemoNewCD
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run a one-line script
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'jtech.com'
    needs: build  
    steps:
    - name: run a one-line script
      run: echo Deploy Dev
      
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'jtech.com'
    needs: deploy-dev 
    steps:
    - name: run a one-line script
      run: echo Deploy HMG
      
  
